[Appearance]
color_scheme_path=/usr/share/qt6ct/colors/darker.conf
custom_palette=true
icon_theme=Tela-circle-grey
standard_dialogs=default
style=Breeze

[Fonts]
fixed="Noto Sans Mono,10,-1,5,50,0,0,0,0,0,Regular"
general="Noto Sans,10,-1,5,50,0,0,0,0,0,Regular"
