#aquí van todos los programas que queremos que se abran apenas se inicia hyperland
#─────────────────────────────────────────────

#---NECESITAN SUDO----


#---NO SUDO----

exec-once = hypridle
exec-once = ~/.config/inicializador/init.sh
exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = ags run ~/.config/ags/
#exec-once = ~/.config/hypr/scripts/boot-healthcheck.sh
#exec-once = awww-daemon
exec-once = ~/.config/hypr/scripts/wallpaper.sh
#exec-once = wl-paste --watch cliphist store
exec-once = ~/.config/hypr/scripts/battery-monitor.sh
#exec-once = ~/.config/hypr/scripts/temp-monitor.sh
#exec-once = ~/.config/hypr/scripts/ram-monitor.sh
#exec-once = ~/.config/hypr/scripts/disk-monitor.sh
#exec-once = ~/.config/hypr/scripts/oom-monitor.sh
#exec-once = ~/.config/hypr/scripts/wifi-monitor.sh
#exec-once = ~/.config/hypr/scripts/usb-monitor.sh
exec-once = ~/.config/hypr/scripts/bt-monitor.sh
