#aquí van todos los programas que queremos que se abran apenas se inicia hyperland
#─────────────────────────────────────────────

#---NECESITAN SUDO----


#---NO SUDO----

exec-once = hypridle
exec-once = ~/.config/inicializador/init.sh
exec-once = ags run ~/.config/ags/
exec-once = awww-daemon
exec-once = ~/.config/hypr/scripts/wallpaper.sh
exec-once = wl-paste --watch cliphist store
