#configuracion de monitores

#monitor(conector monitor,resolucion@frecuencia,coordenadas del monitor (0,0) es interno a la izquierda,escala)
#monitor = eDP-1, 1920x1200@60, 0x0, 1,33

monitor = desc:BOE 0x0CDD 0x0000FFA1, 1920x1200@60, 0x0, 1.33

#añadir un ato conf para pantallas sin configurar
monitor = , preferred, auto, 1

#mejora la nitidez en apps XWAYLAND
xwayland {
    force_zero_scaling = true
}
