#aqui se gestio los modos de ahorro de pantalla-> suspensión , bajar brillo ...
#─────────────────────────────────────────────
general {
    #configurar para mandar al lock
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
}

#apagar pantalla / el OS ya libera ram si puede auto
listener {
    timeout = 600          # 10 min — apagar pantalla
    on-timeout = hyprctl dispatch dpms off 
    on-resume = hyprctl dispatch dpms on
}

#mandar al lock
listener {
    timeout = 630        # 10.30 min — bloquear
    on-timeout = hyprlock
}

#suspender pc
listener {
    timeout =  660         # 11 min — suspender
    on-timeout = systemctl suspend
}