# Generado por AGS · Ajustes > Dispositivos. No editar a mano.
input {
    kb_layout = es
    kb_variant = 
    repeat_rate = 25
    repeat_delay = 600
    numlock_by_default = true
    follow_mouse = 1
    sensitivity = 0.00
    accel_profile = adaptive
    force_no_accel = false
    left_handed = false
    natural_scroll = false
    scroll_factor = 1.00

    touchpad {
        natural_scroll = true
        scroll_factor = 0.10
        tap-to-click = true
        tap_button_map = lrm
        disable_while_typing = true
        clickfinger_behavior = false
        middle_button_emulation = false
        drag_lock = false
    }
}
