# Configuración genérica: usa la resolución preferida del monitor a escala 1.
# Después se puede ajustar desde la sección Pantalla de AGS.
monitor = , preferred, auto, 1

#mejora la nitidez en apps XWAYLAND
xwayland {
    force_zero_scaling = true
}
