#aqui van reglas de ventanas


# Tearing en juegos (requiere general:allow_tearing = true, en gaming.conf).
# Ajusta el match a tus juegos; steam_app_* cubre casi todo lo de Steam.
windowrule {
    name = tearing-games
    match:class = ^(steam_app_.*|gamescope|.*\.exe)$
    immediate = true
}


# Firefox & Kitty opacity
windowrule {
    name = firefox-opacity
    match:class = firefox
    opacity = 1.0 override 1.0 override
}

windowrule {
    name = kitty-opacity
    match:class = kitty
    opacity = 1.0 override 1.0 override
}

# Calculadora
windowrule {
    name = qalculate
    match:class = qalculate-gtk
    float = true
}

# Waybar and Wifi Panel
windowrule {
    name = wifi-panel
    match:class = wifi-panel
    float = true
    move = 1540 44
    size = 340 600
    pin = true
}

layerrule {
    name = waybar-layer
    match:namespace = waybar
    blur = true
}

layerrule {
    name = orion-acrilico
    match:namespace = orion
    blur = true
    ignore_alpha = 0.1
}

layerrule {
    name = quick-settings-acrilico
    match:namespace = quick-settings
    blur = true
    ignore_alpha = 0.1
}

layerrule {
    name = notificaciones-acrilico
    match:namespace = notification-panel
    blur = true
    ignore_alpha = 0.1
}

layerrule {
    name = osd-acrilico
    match:namespace = osd
    blur = true
    ignore_alpha = 0.1
}



# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule {
#     name = no-gaps-wtv1
#     match:float = false
#     match:workspace = w[tv1]
#
#     border_size = 0
#     rounding = 0
# }
#
# windowrule {
#     name = no-gaps-f1
#     match:float = false
#     match:workspace = f[1]
#
#     border_size = 0
#     rounding = 0
# }


##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}
