#aqui van variables internas de hyprland

$mainMod = SUPER # Sets "Windows" ("SUPER") key as main modifier
$terminal = kitty
$fileManager = dolphin
$menu = hyprlauncher
$ruta_captura_pantalla = ~/Imágenes/Capturas_Pantalla/ 
$ruta_grabacion_pantalla = ~/Videos/Grabaciones_Pantalla